Repository jupytercalpoly/Jupyter-Bifrost, pull requests merged in 2021-08, with the labels that each got.

#71 Axis Slider History
  examples/introduction.ipynb
  src/components/Graph.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/components/ui-widgets/RangeSlider.tsx
Labels: enhancement

#73 update readme
  README.md
Labels: documentation

#69 Axis Scaling
  examples/introduction.ipynb
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/hooks/bifrost-model.ts
  src/modules/VegaEncodings.ts
Labels: enhancement

#63 Graph Data Pills
  examples/introduction.ipynb
  src/assets/AggregateIcon.tsx
  src/assets/CategoryIcon.tsx
  src/assets/FilterIcon.tsx
  src/assets/NumericalIcon.tsx
  src/assets/icons/SliderIcon.tsx
  src/components/Graph.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/components/Sidebar/Tabs/VariablesTab.tsx
  src/components/ui-widgets/GraphPill.tsx
  src/modules/VegaFilters.ts
  src/theme.ts
Labels: enhancement

#72 Replace compassQL with Draco
  .husky/pre-commit
  bifrost_jupyter_extension/__init__.py
  bifrost_jupyter_extension/bifrost.py
  jest.config.js
  package.json
  src/__tests__/mocks/draco-core.ts
  src/assets/icons/TickChartIcon.tsx
  src/components/Onboarding/ChartChooser.tsx
  src/components/Onboarding/ChartFilter.tsx
  src/components/Onboarding/ColumnSelectorSidebar.tsx
  src/components/Sidebar/Sidebar.tsx
  src/widget.ts
Labels: enhancement

#82 Collapsible Side Bar
  package.json
  src/assets/icons/SideBarCollapsibleButtonIcon.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/VisualizationScreen.tsx
  yarn.lock
Labels: enhancement

#88 Fixed Size/Styling issues
  bifrost_jupyter_extension/bifrost.py
  examples/introduction.ipynb
  src/assets/icons/TickChartIcon.tsx
  src/components/BifrostReactWidget.tsx
  src/components/Onboarding/ChartChooser.tsx
  src/components/Onboarding/ChartFilter.tsx
  src/components/Onboarding/ColumnSelectorSidebar.tsx
  src/components/Onboarding/OnboardingWidget.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/Tabs/CustomizationTab/CustomizationTab.tsx
  src/components/Sidebar/Tabs/DataTab.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/components/Sidebar/Tabs/HistoryTab.tsx
  src/components/Sidebar/Tabs/MarkTab.tsx
  src/components/VisualizationScreen.tsx
  src/modules/VegaEncodings.ts
  src/modules/VegaFilters.ts
Labels: bug

#91 Binning
  examples/introduction.ipynb
  src/components/Onboarding/KeyboardNav.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/hooks/bifrost-model.ts
Labels: bug, enhancement

#93 Pill type toggle
  examples/introduction.ipynb
  src/components/Sidebar/Tabs/DataTab.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/components/ui-widgets/GraphPill.tsx
Labels: enhancement

#94 Performance Sampling
  bifrost_jupyter_extension/bifrost.py
  examples/introduction.ipynb
  src/components/Onboarding/OnboardingWidget.tsx
  src/hooks/bifrost-model.ts
  src/widget.ts
Labels: enhancement

#99 Pill Type Guard
  src/components/Sidebar/Tabs/DataTab.tsx
Labels: bug

#92 DataFrame Autosave
  bifrost_jupyter_extension/__init__.py
  bifrost_jupyter_extension/bifrost.py
  examples/introduction.ipynb
  src/components/Sidebar/Sidebar.tsx
  src/hooks/useSpecHistory.ts
  src/modules/VegaPandasTranslator.ts
  src/widget.ts
Labels: enhancement

#104 Help Screen
  examples/introduction.ipynb
  package.json
  src/components/HelpScreen/HelpScreen.tsx
  src/components/HelpScreen/articles.ts
  src/components/NavBar.tsx
  src/components/Onboarding/ChartChooser.tsx
  src/components/VisualizationScreen.tsx
  yarn.lock
Labels: enhancement

#113 History Descriptions
  src/components/Graph.tsx
  src/components/Onboarding/ChartChooser.tsx
  src/components/Sidebar/Tabs/AddPillScreen.tsx
  src/components/Sidebar/Tabs/CustomizationTab/CustomizationTab.tsx
  src/components/Sidebar/Tabs/EditTab.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/components/Sidebar/Tabs/HistoryTab.tsx
  src/hooks/bifrost-model.ts
  src/hooks/useSpecHistory.ts
Labels: enhancement

#115 Updated Sidebar
  src/components/Sidebar/Sidebar.tsx
Labels: enhancement

#114 Chart Chooser Updates
  docs/source/_static/embed-bundle.js.LICENSE.txt
  src/components/Onboarding/ChartChooser.tsx
  src/components/Onboarding/ChartFilter.tsx
  src/components/Tooltip.tsx
Labels: enhancement

#119 Sampling Slider
  examples/introduction.ipynb
  jupyter_bifrost/bifrost.py
  src/components/Graph.tsx
  src/components/Onboarding/NavHeader.tsx
  src/components/Onboarding/OnboardingScreen.ts
  src/components/Onboarding/OnboardingWidget.tsx
  src/components/Sidebar/Tabs/EditTab.tsx
  src/components/Sidebar/Tabs/NearByTab.tsx
  src/components/ui-widgets/Loader.tsx
  src/components/ui-widgets/Slider.tsx
  src/hooks/bifrost-model.ts
  src/widget.ts
Labels: enhancement

#126 Mark Icon Filters
  src/assets/icons/chartIcons/ChartIcons.ts
  src/components/BifrostReactWidget.tsx
  src/components/Sidebar/Tabs/EditTab.tsx
  src/modules/VegaEncodings.ts
Labels: enhancement

#134 Fixed Lingering Filters
  src/components/Sidebar/Tabs/EditTab.tsx
  src/modules/utils.ts
Labels: bug

#136 Bug Fixes Round 2
  examples/introduction.ipynb
  src/components/BifrostReactWidget.tsx
  src/components/Graph.tsx
  src/components/HelpScreen/HelpScreen.tsx
  src/components/Onboarding/ChartChooser.tsx
  src/components/Onboarding/ColumnSelectorSidebar.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/Tabs/EditTab.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/components/Sidebar/Tabs/HistoryTab.tsx
  src/components/ui-widgets/Modal.tsx
  src/components/ui-widgets/RangeSlider.tsx
Labels: enhancement

#140 Round 1 on Bugs 3
  jupyter_bifrost/bifrost.py
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/components/ui-widgets/RangeSlider.tsx
  src/modules/utils.ts
Labels: bug

#144 Fixed Filter Ranges
  bifrost_jupyter_extension/bifrost.py
  jupyter_bifrost/bifrost.py
  src/components/Graph.tsx
  src/components/Sidebar/Tabs/EditTab.tsx
  src/components/Sidebar/Tabs/FilterScreen.tsx
  src/widget.ts
Labels: bug, documentation

#139 Box and whisker bug
  examples/introduction.ipynb
  src/components/Sidebar/Tabs/AddPillScreen.tsx
  src/components/Sidebar/Tabs/EditTab.tsx
  src/modules/VegaEncodings.ts
Labels: bug

#141 GraphPill Padding and Aggregation Bug
  src/components/ui-widgets/GraphPill.tsx
  src/modules/VegaPandasTranslator.ts
Labels: bug

#145 Scaling and Binning Pandas code
  src/modules/VegaEncodings.ts
  src/modules/VegaPandasTranslator.ts
Labels: enhancement
